name: 'Setup DDEV'
description: 'Install and configure DDEV with pinned action SHA'

runs:
  using: 'composite'
  steps:
    - name: Setup DDEV
      uses: ddev/github-action-setup-ddev@fdf2f5c97943bae638f31df6df86f1defa6210c0 # v1
